syan-tibco/tp-helm-charts

- charts/dp-core-infrastructure/Chart.lock
- charts/dp-core-infrastructure/Chart.yaml
- charts/dp-core-infrastructure/charts/tp-cp-proxy/.helmignore
- charts/dp-core-infrastructure/charts/tp-cp-proxy/Chart.yaml
- charts/dp-core-infrastructure/charts/tp-cp-proxy/image-tags.txt
- charts/dp-core-infrastructure/charts/tp-cp-proxy/templates/_consts.tpl
- charts/dp-core-infrastructure/charts/tp-cp-proxy/templates/_generated.tpl
- charts/dp-core-infrastructure/charts/tp-cp-proxy/templates/_shared.tpl
- charts/dp-core-infrastructure/charts/tp-cp-proxy/templates/deployment.yaml
- charts/dp-core-infrastructure/charts/tp-cp-proxy/templates/network_policy.yaml
- charts/dp-core-infrastructure/charts/tp-cp-proxy/templates/service.yaml
- charts/dp-core-infrastructure/charts/tp-cp-proxy/values.yaml
- charts/dp-core-infrastructure/charts/tp-provisioner-agent/templates/_generated.tpl
- charts/dp-core-infrastructure/charts/tp-provisioner-agent/templates/deployment.yaml
- charts/dp-core-infrastructure/charts/tp-provisioner-agent/templates/rbac.yaml
- charts/dp-core-infrastructure/charts/tp-provisioner-agent/values.yaml
- charts/dp-core-infrastructure/charts/tp-tibtunnel/Chart.yaml
- charts/dp-core-infrastructure/charts/tp-tibtunnel/templates/_generated.tpl
- charts/dp-core-infrastructure/charts/tp-tibtunnel/templates/deployment.yaml
- charts/dp-core-infrastructure/charts/tp-tibtunnel/values.yaml
- charts/dp-core-infrastructure/image-tags.txt
- charts/dp-core-infrastructure/values.yaml
1. Added cp proxy
2. New Provisioner-agent chart
3. New tibtunnel chart.
> updated dp-core-infrastructure to 1.0.66

- charts/dp-core-infrastructure/Chart.lock
error chart.lock out of sync, I had to run helm dep update locally.
> fixed chart.lock

- charts/dp-ems-on-ftl/.helmignore
- charts/dp-ems-on-ftl/Chart.yaml
- charts/dp-ems-on-ftl/scripts/load-ems-init-json.sh
- charts/dp-ems-on-ftl/scripts/mk-common.conf.sh
- charts/dp-ems-on-ftl/scripts/mk-fluentbits.conf.sh
- charts/dp-ems-on-ftl/scripts/mk-ftlserver.yaml.sh
- charts/dp-ems-on-ftl/scripts/mk-output.conf.sh
- charts/dp-ems-on-ftl/scripts/mk-tibemsd-ftl.json.sh
- charts/dp-ems-on-ftl/scripts/mk-watchdog.yaml.sh
- charts/dp-ems-on-ftl/templates/_dp.helpers.tpl
- charts/dp-ems-on-ftl/templates/_ems.dp.helpers.tpl
- charts/dp-ems-on-ftl/templates/ems-init.job.yaml
- charts/dp-ems-on-ftl/templates/ftl.stateful.yaml
- charts/dp-ems-on-ftl/templates/ftl.svc.yaml
- charts/dp-ems-on-ftl/templates/script.cm.yaml
- charts/dp-ems-on-ftl/values.yaml
checking before I merge :) ...
you can ignore fluentbits config file - no fluentbits running yet ...
> Add first dp-ems-on-ftl chart

- charts/dp-config-namespace/.helmignore
- charts/dp-config-namespace/Chart.yaml
- charts/dp-config-namespace/README.md
- charts/dp-config-namespace/templates/NOTES.txt
- charts/dp-config-namespace/templates/_helpers.tpl
- charts/dp-config-namespace/templates/cluster-role-binding.yaml
- charts/dp-config-namespace/templates/cluster-role.yaml
- charts/dp-config-namespace/templates/role-binding.yaml
- charts/dp-config-namespace/templates/sa.yaml
- charts/dp-config-namespace/values.yaml
- charts/tp-provisioner-agent/templates/_shared.tpl
The assumption is that customer has created the namespaces and labeled those with the DP ID.
After that, customer has to deploy this chart in the namespace (where infra will be deployed) and provide the values as follows
> global:
>   tibco:
>     serviceAccount: "service-account" # customer provided service account
>     dataPlaneId: "abcd"
> 
> #this creates cluster roles which are not namespaced
> clusterRole:
>   create: true
>   createBinding: true
> 
> #this creates namespaces and role-bindings in those namespaces
> namespaces:
>   - name: "namespacea"
>     createBinding: true
>   - name: "namespaceb"
>     createBinding: true
>   - name: "namespacec"
>     createBinding: true
> 
>
> PDP-816: Create sa, cluster-roles, cluster-role-binding,role-binding, for given namespaces.

- charts/istio-crd/Chart.yaml
- charts/istio-istiod/Chart.yaml
- charts/istio-istiod/overrides/cic2.yaml
- charts/istio-istiod/overrides/gcp.yaml
- charts/istio-istiod/templates/deployment.yaml
- charts/istio-istiod/templates/fluent-bit-configmap.yaml
- charts/istio-istiod/values.yaml
Adding fluent-bit as a sidecar for istiod
> Refs #EIN-11491 Addng fluent-bit as a sidecar for istiod

- charts/bwprovisioner/config/otel/parsers.conf
- charts/flogoprovisioner/config/otel/parsers.conf
The regex for both BW and Flogo app log format.
> Updated the log parser for both bw and flogo

- charts/tibco-hub/Chart.yaml
- charts/tibco-hub/templates/_helpers.tpl
- charts/tibco-hub/templates/backstage-deployment.yaml
- charts/tibco-hub/values.yaml
Edited the template logic to support dynamic image for the Jfrog containerRegistry url.
#PLTDX-668
> Changed the image dynamically for the Jfrog containerRegistry url

- charts/tibco-hub/Chart.yaml
- charts/tibco-hub/templates/backstage-deployment.yaml
CCRB Approved: https://jira.tibco.com/browse/PLTDX-724
> add network policy label to tibco hub pod

- charts/tibco-hub/Chart.yaml
- charts/tibco-hub/templates/backstage-deployment.yaml
#PLTDX-668
Released chart version 1.0.23
> Added secret file for Jfrog environment.

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/values.yaml
> Done Jfrog related changes and released chart version 1.0.26

- charts/tp-dp-monitor-agent/Chart.yaml
- charts/tp-dp-monitor-agent/templates/_consts.tpl
- charts/tp-dp-monitor-agent/templates/_generated.tpl
Changed the jfrogSourceValue entry in _consts.tpl, bumped version accordingly.
> Use new jfrogSourceRepo value.

- docs/dp-cluster-workshop/aks/README.md
- docs/dp-cluster-workshop/eks/README.md
Tested with:
```
$ helm repo add tibco-public https://tibcosoftware.github.io/tp-helm-charts
"tibco-public" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "tibco-public" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm pull tibco-public/dp-config-aks
```
> PDP-1461: correct public chart url

- docs/dp-cluster-workshop/aks/README.md
- docs/dp-cluster-workshop/eks/README.md
https://docs.google.com/document/d/1VOaVQWsE_u9XY6G1HWjIevWdRDwaNjoEidtFdPtEF4U/edit
> PDP-1499: PM recommended README fixes

- charts/msg-ems-tp/Chart.yaml
- charts/msg-ems-tp/scripts/health-watcher.sh
- charts/msg-ems-tp/scripts/load-ems-init-json.sh
- charts/msg-ems-tp/scripts/mk-common.conf.sh
- charts/msg-ems-tp/scripts/mk-fluentbits.conf.sh
- charts/msg-ems-tp/scripts/mk-ftlserver.yaml.sh
- charts/msg-ems-tp/scripts/mk-output.conf.sh
- charts/msg-ems-tp/scripts/mk-parsers.conf.sh
- charts/msg-ems-tp/scripts/mk-runPromCollector.sh
- charts/msg-ems-tp/scripts/mk-tibemsd-ftl.json.sh
- charts/msg-ems-tp/scripts/mk-watchdog.yaml.sh
- charts/msg-ems-tp/scripts/pod-stats.sh
- charts/msg-ems-tp/templates/_dp.helpers.tpl
- charts/msg-ems-tp/templates/_ems.dp.helpers.tpl
- charts/msg-ems-tp/templates/client.cm.yaml
- charts/msg-ems-tp/templates/ems-init.job.yaml
- charts/msg-ems-tp/templates/ems-logs.pvc.yaml
- charts/msg-ems-tp/templates/ems-preinstall.job.yaml
- charts/msg-ems-tp/templates/ems-uninstall.job.yaml
- charts/msg-ems-tp/templates/ems-upgrade.job.yaml
- charts/msg-ems-tp/templates/ftl.stateful.yaml
- charts/msg-ems-tp/templates/ftl.svc.yaml
- charts/msg-ems-tp/templates/ops.stateful.yaml
- charts/msg-ems-tp/templates/params.cm.yaml
- charts/msg-ems-tp/templates/script.cm.yaml
- charts/msg-ems-tp/values.yaml
First set of 1.0.1 msg-ems-tp chart fixes ...
> publish new chart: msg-ems-tp-1.0.24

- charts/msg-ems-tp/Chart.yaml
- charts/msg-ems-tp/scripts/health-watcher.sh
- charts/msg-ems-tp/scripts/mk-tibemsd-ftl.json.sh
- charts/msg-ems-tp/templates/_dp.helpers.tpl
- charts/msg-ems-tp/templates/_ems.dp.helpers.tpl
- charts/msg-ems-tp/templates/emsactive.svc.yaml
- charts/msg-ems-tp/templates/ftl.stateful.yaml
- charts/msg-ems-tp/templates/ftl.svc.yaml
Special emsactive pod service logic
> 1.0.1 chart updates :  msg-ems-tp-1.0.25

- charts/dp-config-aks/Chart.yaml
- charts/dp-configure-namespace/Chart.yaml
changed appVersion for aks & dp-configure-namespace chart
> changed appVersion for aks & dp-configure-namespace chart

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/values.yaml
Updated tibco hub app version to 1.0.1 and released version 1.0.28
> Updated tibco hub app version to 1.0.1 and released version 1.0.28

- docs/dp-cluster-workshop/aks/README.md
- docs/dp-cluster-workshop/eks/README.md
Change in document for grammar change
> PDP-1499: readme update for typos

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/values.yaml
Released tibco hub version 1.0.31.
#PLTDX-833
#PLTDX-872
> Released tibco hub version 1.0.31.

- charts/o11y-service/Chart.yaml
- charts/o11y-service/values.yaml
Please find the PR details here for the corresponding o11y service changes.
https://github.com/tibco/tp-o11y-service/pull/35
> O11y-Service Chart version: 1.0.54, image tag: 813

- charts/msg-ems-tp/Chart.yaml
- charts/msg-ems-tp/templates/_dp.helpers.tpl
1.0.1.27 build - Ready for platform-qa
> publish new chart: msg-ems-tp-1.0.27

- charts/tibco-developer-hub/Chart.yaml
- charts/tibco-developer-hub/values.yaml
Released tibco hub version 1.0.32.
#PLTDX-881
> Released tibco hub version 1.0.32.

- docs/dp-cluster-workshop/aks/README.md
Adding comments for EMS recommended values
> PDP-1528: mention EMS recommended values

- charts/dp-config-aks/Chart.yaml
- charts/dp-config-aks/values.yaml
- docs/dp-cluster-workshop/aks/README.md
Following are the changes:
1. use skuName (and not skuname)
2. relclaim policy required in Azure files as well
3. chart version should be 1.0.16
> PDP-1528: address comments for using skuName, relclaim policy required in Azure files & chart version should be 1.0.16

- docs/dp-cluster-workshop/aks/README.md
After uncommenting the line for skuName, it should appear to be object of parameters.
> PDP-1528: Fix indetation after uncomment
